<?php
namespace App\Services;

use Illuminate\Support\Facades\Storage;

class AWSService
{
    public static function upload($file, $keys)
    {
        //upload to amazon s3
        ini_set('max_execution_time', '600');
        config(['filesystems.disks.s3.key' => $keys->AWS_ACCESS_KEY_ID]);
        config(['filesystems.disks.s3.secret' => $keys->AWS_SECRET_ACCESS_KEY]);
        config(['filesystems.disks.s3.region' => $keys->AWS_DEFAULT_REGION]);
        config(['filesystems.disks.s3.bucket' => $keys->AWS_BUCKET]);

        //The file name generated by laravel s3 package
        $s3_file_path = Storage::disk('s3')->put('social-files', $file, 'public');
        $s3_file_path = Storage::disk('s3')->url($s3_file_path);
        return $s3_file_path;
    }
}